package dev.iadev.application.assembler;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Tests for SummaryTableBuilder — builds generation summary table and settings section for
 * README.md.
 */
@DisplayName("SummaryTableBuilder")
class SummaryTableBuilderTest {

    private final SummaryTableBuilder builder = new SummaryTableBuilder();

    @Nested
    @DisplayName("buildGenerationSummary")
    class BuildGenerationSummary {

        @Test
        @DisplayName("contains 7 component rows")
        void build_whenCalled_containsSevenComponents(@TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary = builder.buildGenerationSummary(claudeDir);

            assertThat(summary).contains("| Component | Count |").contains("|-----------|-------|");
            int dataRows = 0;
            for (String line : summary.split("\n")) {
                if (line.startsWith("| ")
                        && !line.startsWith("| Component")
                        && !line.startsWith("|---")) {
                    dataRows++;
                }
            }
            assertThat(dataRows).isEqualTo(7);
        }

        @Test
        @DisplayName("contains ia-dev-env version")
        void build_whenCalled_containsVersion(@TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary = builder.buildGenerationSummary(claudeDir);

            assertThat(summary).contains("Generated by `ia-dev-env" + " v0.1.0`.");
        }

        @Test
        @DisplayName("includes all component labels")
        void build_whenCalled_includesAllLabels(@TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary = builder.buildGenerationSummary(claudeDir);

            assertThat(summary)
                    .contains("Rules (.claude)")
                    .contains("Skills (.claude)")
                    .contains("Knowledge Packs (.claude)")
                    .contains("Agents (.claude)")
                    .contains("Hooks (.claude)")
                    .contains("Settings (.claude)")
                    .contains("Plan Templates (.claude)")
                    .doesNotContain("AGENTS.md")
                    .doesNotContain("Skills (.agents)")
                    .doesNotContain("Codex (.codex)");
        }

        @Test
        @DisplayName("counts plan templates when present")
        void build_withTemplates_countsPlanTemplates(@TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);
            Path claudeTemplates = Files.createDirectories(claudeDir.resolve("templates"));
            for (int i = 1; i <= 12; i++) {
                Files.writeString(
                        claudeTemplates.resolve("_TEMPLATE-PLAN-" + i + ".md"),
                        "content",
                        StandardCharsets.UTF_8);
            }

            String summary = builder.buildGenerationSummary(claudeDir);

            assertThat(summary).contains("Plan Templates (.claude)" + " | 12 |");
        }

        private Path setupMinimalOutput(Path tempDir) throws IOException {
            return Files.createDirectories(tempDir.resolve(".claude"));
        }
    }

    @Nested
    @DisplayName("buildSettingsSection")
    class BuildSettingsSection {

        @Test
        @DisplayName("contains settings.json description")
        void build_whenCalled_containsSettingsJsonDesc() {
            String section = builder.buildSettingsSection();

            assertThat(section)
                    .contains("### settings.json")
                    .contains("permissions.allow")
                    .contains("### settings.local.json")
                    .contains("Local overrides");
        }
    }
}
