package dev.iadev.application.assembler;

import static org.assertj.core.api.Assertions.assertThat;

import dev.iadev.domain.model.Platform;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/** Tests for platform-filtered generation summary in SummaryTableBuilder. */
@DisplayName("SummaryTableBuilder — platform filtering")
class SummaryTableBuilderPlatformTest {

    private final SummaryTableBuilder builder = new SummaryTableBuilder();

    @Nested
    @DisplayName("buildGenerationSummary with platforms")
    class FilteredSummary {

        @Test
        @DisplayName("claude-only shows all claude rows" + " (single user-selectable == no filter)")
        void build_claudeOnly_showsAllClaudeRows(@TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary =
                    builder.buildGenerationSummary(claudeDir, Set.of(Platform.CLAUDE_CODE));

            // With only CLAUDE_CODE selectable, specifying
            // it is the same as "all" — no filter applied.
            assertThat(summary)
                    .contains("Rules (.claude)")
                    .contains("Skills (.claude)")
                    .contains("Knowledge Packs (.claude)")
                    .contains("Agents (.claude)")
                    .contains("Hooks (.claude)")
                    .contains("Settings (.claude)")
                    .contains("Plan Templates (.claude)")
                    .doesNotContain("(.github)")
                    .doesNotContain("(.codex)");
        }

        @Test
        @DisplayName("empty platforms shows all rows")
        void build_emptyPlatforms_showsAllRows(@TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary = builder.buildGenerationSummary(claudeDir, Set.of());

            assertThat(summary)
                    .contains("(.claude)")
                    .doesNotContain("AGENTS.md")
                    .doesNotContain("(.agents)");
        }

        @Test
        @DisplayName("all user-selectable shows all rows")
        void build_allSelectable_showsAllRows(@TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary =
                    builder.buildGenerationSummary(claudeDir, Platform.allUserSelectable());

            assertThat(summary).contains("(.claude)");
        }

        @Test
        @DisplayName("always contains version footer")
        void build_anyPlatform_containsVersion(@TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary =
                    builder.buildGenerationSummary(claudeDir, Set.of(Platform.CLAUDE_CODE));

            assertThat(summary).contains("Generated by `ia-dev-env");
        }
    }

    private Path setupMinimalOutput(Path tempDir) throws IOException {
        Path claudeDir = Files.createDirectories(tempDir.resolve(".claude"));
        return claudeDir;
    }
}
