package dev.iadev.smoke;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledOnOs;
import org.junit.jupiter.api.condition.OS;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * Verifies the CI-Watch Integrity contract (RULE-045-05) is generated by every profile.
 *
 * <p>EPIC-0078 rules-consolidation-essentials: Rule 45 was migrated from {@code
 * .claude/rules/45-ci-watch-integrity.md} to the lifecycle KP at {@code
 * .claude/knowledge/lifecycle/ci-watch-integrity.md}. This test has been updated to validate the
 * equivalent content at its new location.
 */
@DisplayName("Rule45CiWatchIntegrityTest — CI-Watch KP carries 8 exit codes + canonical sections")
@DisabledOnOs(
        value = OS.WINDOWS,
        disabledReason = "POSIX path resolution; mirrors sibling smoke tests.")
class Rule45CiWatchIntegrityTest extends SmokeTestBase {

    // rules-consolidation-essentials: Rule 45 migrated to lifecycle KP.
    // Canonical sections: Exit Codes Matrix, Mandatory Invocation Sites, Forbidden, Audit Contract.
    private static final List<String> CANONICAL_SECTIONS =
            List.of(
                    "## Exit Codes Matrix",
                    "## Mandatory Invocation Sites",
                    "## Forbidden",
                    "## Audit Contract");

    // Exit codes in the KP table format.
    private static final List<String> EXPECTED_EXIT_CODES =
            List.of(
                    "SUCCESS",
                    "CI_PENDING_PROCEED",
                    "CI_FAILED",
                    "TIMEOUT",
                    "PR_ALREADY_MERGED",
                    "NO_CI_CONFIGURED",
                    "PR_CLOSED",
                    "PR_NOT_FOUND");

    // KP path in generated output (was .claude/rules/45-ci-watch-integrity.md).
    private static final String CI_WATCH_KP_PATH =
            ".claude/knowledge/lifecycle/ci-watch-integrity.md";

    @ParameterizedTest(name = "[{0}]")
    @MethodSource("dev.iadev.smoke.SmokeProfiles#profiles")
    @DisplayName("CI-Watch KP is generated for every profile")
    void rule45_existsInEveryProfile(String profile) throws IOException {
        runPipeline(profile);
        Path kp = getOutputDir(profile).resolve(CI_WATCH_KP_PATH);

        assertThat(kp).as("profile %s: ci-watch-integrity KP must exist", profile).exists();
    }

    @ParameterizedTest(name = "[{0}]")
    @MethodSource("dev.iadev.smoke.SmokeProfiles#profiles")
    @DisplayName("CI-Watch KP declares canonical sections")
    void rule45_declaresCanonicalSections(String profile) throws IOException {
        runPipeline(profile);
        Path kp = getOutputDir(profile).resolve(CI_WATCH_KP_PATH);
        String body = Files.readString(kp, StandardCharsets.UTF_8);

        for (String section : CANONICAL_SECTIONS) {
            assertThat(body)
                    .as("profile %s: CI-Watch KP must declare '%s'", profile, section)
                    .contains(section);
        }
    }

    @ParameterizedTest(name = "[{0}]")
    @MethodSource("dev.iadev.smoke.SmokeProfiles#profiles")
    @DisplayName("CI-Watch KP lists all 8 stable exit codes")
    void rule45_listsAllEightExitCodes(String profile) throws IOException {
        runPipeline(profile);
        Path kp = getOutputDir(profile).resolve(CI_WATCH_KP_PATH);
        String body = Files.readString(kp, StandardCharsets.UTF_8);

        for (String code : EXPECTED_EXIT_CODES) {
            assertThat(body)
                    .as("profile %s: CI-Watch KP must reference exit code %s", profile, code)
                    .contains(code);
        }
    }

    @Test
    @DisplayName("reference golden CI-Watch KP references RULE-045-05")
    void rule45_referencesRule045_05() throws IOException {
        Path kp = repoRoot().resolve("src/test/resources/golden/java-spring/" + CI_WATCH_KP_PATH);
        String body = Files.readString(kp, StandardCharsets.UTF_8);

        assertThat(body)
                .as("CI-Watch KP must explicitly reference RULE-045-05")
                .contains("RULE-045-05");
    }

    private Path repoRoot() {
        Path cwd = Path.of("").toAbsolutePath();
        return cwd.getFileName().toString().equals("java") ? cwd.getParent() : cwd;
    }
}
