package dev.iadev.smoke;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledOnOs;
import org.junit.jupiter.api.condition.OS;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies Rule 45 (CI-Watch Integrity) is generated by every profile
 * with the canonical sections and the 8 stable exit codes from
 * {@code x-pr-watch-ci} (RULE-045-05).
 *
 * <p>Story-0057-0003 promotes the previously inline RULE-045-* contract
 * to a first-class rule under {@code .claude/rules/}. This test guards
 * against regression of the rule's structural integrity.</p>
 */
@DisplayName("Rule45CiWatchIntegrityTest — Rule 45 carries 8 exit codes + canonical sections")
@DisabledOnOs(
        value = OS.WINDOWS,
        disabledReason = "POSIX path resolution; mirrors sibling smoke tests.")
class Rule45CiWatchIntegrityTest extends SmokeTestBase {

    private static final List<String> CANONICAL_SECTIONS = List.of(
            "## Purpose",
            "## Exit Codes Matrix",
            "## Fallback Matrix",
            "## `--no-ci-watch` Constraints",
            "## Mandatory Invocation Sites",
            "## Forbidden",
            "## Audit");

    private static final List<String> EXPECTED_EXIT_CODES = List.of(
            "`SUCCESS`",
            "`CI_PENDING_PROCEED`",
            "`CI_FAILED`",
            "`TIMEOUT`",
            "`PR_ALREADY_MERGED`",
            "`NO_CI_CONFIGURED`",
            "`PR_CLOSED`",
            "`PR_NOT_FOUND`");

    @ParameterizedTest(name = "[{0}]")
    @MethodSource("dev.iadev.smoke.SmokeProfiles#profiles")
    @DisplayName("Rule 45 is generated for every profile")
    void rule45_existsInEveryProfile(String profile) throws IOException {
        runPipeline(profile);
        Path rule = getOutputDir(profile)
                .resolve(".claude/rules/45-ci-watch-integrity.md");

        assertThat(rule)
                .as("profile %s: Rule 45 file must exist", profile)
                .exists();
    }

    @ParameterizedTest(name = "[{0}]")
    @MethodSource("dev.iadev.smoke.SmokeProfiles#profiles")
    @DisplayName("Rule 45 declares all 7 canonical sections")
    void rule45_declaresCanonicalSections(String profile)
            throws IOException {
        runPipeline(profile);
        Path rule = getOutputDir(profile)
                .resolve(".claude/rules/45-ci-watch-integrity.md");
        String body = Files.readString(rule, StandardCharsets.UTF_8);

        for (String section : CANONICAL_SECTIONS) {
            assertThat(body)
                    .as("profile %s: Rule 45 must declare '%s'",
                            profile, section)
                    .contains(section);
        }
    }

    @ParameterizedTest(name = "[{0}]")
    @MethodSource("dev.iadev.smoke.SmokeProfiles#profiles")
    @DisplayName("Rule 45 lists all 8 stable exit codes")
    void rule45_listsAllEightExitCodes(String profile) throws IOException {
        runPipeline(profile);
        Path rule = getOutputDir(profile)
                .resolve(".claude/rules/45-ci-watch-integrity.md");
        String body = Files.readString(rule, StandardCharsets.UTF_8);

        for (String code : EXPECTED_EXIT_CODES) {
            assertThat(body)
                    .as("profile %s: Rule 45 must reference exit code %s",
                            profile, code)
                    .contains(code);
        }
    }

    @Test
    @DisplayName("reference golden Rule 45 references RULE-045-05")
    void rule45_referencesRule045_05() throws IOException {
        Path rule = repoRoot()
                .resolve("java/src/test/resources/golden/java-spring/"
                        + ".claude/rules/45-ci-watch-integrity.md");
        String body = Files.readString(rule, StandardCharsets.UTF_8);

        assertThat(body)
                .as("Rule 45 must explicitly reference RULE-045-05")
                .contains("RULE-045-05");
    }

    private Path repoRoot() {
        Path cwd = Path.of("").toAbsolutePath();
        return cwd.getFileName().toString().equals("java")
                ? cwd.getParent()
                : cwd;
    }
}
