package dev.iadev.application.assembler;

import dev.iadev.domain.model.Platform;
import dev.iadev.domain.model.ProjectFoundation;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * Builds the generation summary table and settings section for README.md.
 *
 * <p>Generates component counts for all artifact types under the {@code .claude/} directory. Also
 * provides the static settings documentation section. Claude Code is the only user-selectable
 * platform, so the legacy platform-filtering parameter is retained for API stability but every row
 * is always emitted.
 *
 * @see ReadmeTables
 * @see ReadmeUtils
 */
public final class SummaryTableBuilder {

    SummaryTableBuilder() {
        // package-private constructor
    }

    /**
     * Builds the generation summary table with component counts.
     *
     * @param outputDir the .claude/ output directory
     * @return formatted generation summary
     */
    String buildGenerationSummary(Path outputDir) {
        return buildGenerationSummary(outputDir, Set.of());
    }

    /**
     * Builds the generation summary table with component counts. The {@code platforms} parameter is
     * retained for backward-compatible callers but is ignored: the only user-selectable platform is
     * {@link Platform#CLAUDE_CODE}, so every row is always included.
     *
     * @param outputDir the .claude/ output directory
     * @param platforms ignored (retained for API stability)
     * @return formatted generation summary
     */
    String buildGenerationSummary(Path outputDir, Set<Platform> platforms) {
        Object[][] rows = buildSummaryRows(outputDir);
        List<String> lines = new ArrayList<>();
        lines.add("| Component | Count |");
        lines.add("|-----------|-------|");
        for (Object[] row : rows) {
            lines.add("| %s | %s |".formatted(row[0], row[1]));
        }
        lines.add("");
        String ver = ProjectFoundation.DEFAULT.version();
        lines.add("Generated by `ia-dev-env v%s`.".formatted(ver));
        return String.join("\n", lines);
    }

    /**
     * Builds static settings section content.
     *
     * @return formatted settings section
     */
    String buildSettingsSection() {
        return "### settings.json\n"
                + "\n"
                + "Permissions are configured in"
                + " `settings.json`"
                + " under `permissions.allow`.\n"
                + "This controls which Bash commands"
                + " Claude Code"
                + " can run without asking.\n"
                + "\n"
                + "### settings.local.json\n"
                + "\n"
                + "Local overrides (gitignored)."
                + " Use for personal"
                + " preferences or team-specific tools.\n"
                + "\n"
                + "See the files directly for current"
                + " configuration.";
    }

    private static Object[][] buildSummaryRows(Path outputDir) {
        return buildClaudeRows(outputDir);
    }

    private static Object[][] buildClaudeRows(Path outputDir) {
        int kps = ReadmeUtils.countKnowledgePacks(outputDir);
        return new Object[][] {
            {"Rules (.claude)", ReadmeUtils.countRules(outputDir)},
            {"Skills (.claude)", ReadmeUtils.countSkills(outputDir) - kps},
            {"Knowledge Packs (.claude)", kps},
            {"Agents (.claude)", ReadmeUtils.countAgents(outputDir)},
            {"Hooks (.claude)", ReadmeUtils.countHooks(outputDir)},
            {"Settings (.claude)", ReadmeUtils.countSettings(outputDir)},
            {"Plan Templates (.claude)", countPlanTemplates(outputDir, "templates")},
        };
    }

    private static int countPlanTemplates(Path baseDir, String subdir) {
        Path templatesDir = baseDir.resolve(subdir);
        return (int)
                MarkdownFileScanner.listMarkdownFiles(templatesDir).stream()
                        .filter(p -> p.getFileName().toString().startsWith("_TEMPLATE-"))
                        .count();
    }
}
